In [1]:

""" 
Pytorch- open source( ML,DL framework)
. manipulate and process data
. write machine learning algorithms
. use: Tesla: PyTorch to power their self-driving computer vision models, 
       agriculture.
""" 

In [2]:
import torch
torch.__version__

'2.5.1'

In [ ]:
""" 
Tensors represent data in a numerical way.
eg: [colour_channels, height, width] => [3, 224, 224]
           ^                 ^
  (red, green, blue)   (224 pixels)  
  

""" 

In [4]:
"""
 Tensor-speak (the language used to describe tensors)
 
 Scalar : . A single number and in tensor-speak it's a zero dimension tensor.
          . Number of dimensions: 0
          . Lower (a)
"""
# Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [5]:
# Dimensions of a tensor
scalar.ndim

0

In [6]:
# Retrieve the number from the tensor
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [7]:
"""
vector : . A vector is a single dimension tensor but can contain many numbers.
         . eg: vector [3, 2] => describe [bedrooms, bathrooms]
         . A number with direction (e.g. wind speed with direction) but can also have many other numbers
         . Number of dimensions:1
         . 	Lower (y)
"""
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
# Check the number of dimensions of vector
vector.ndim

1

In [9]:
# Check shape of vector
vector.shape

torch.Size([2])

In [10]:
"""
MATRIX : . A 2-dimensional array of numbers
         . Number of dimensions: 2
         . Upper (Q)
"""

# Matrix
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
# Check number of dimensions
MATRIX.ndim


2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
"""
TENSOR : . An n-dimensional array of numbers 
         . Can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector
         . Upper (X)

"""
#  Create Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [16]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
# how to create a tensor of random numbers.
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype


(tensor([[0.1144, 0.0521, 0.1992, 0.6948],
         [0.6013, 0.2675, 0.9360, 0.3266],
         [0.6811, 0.6578, 0.0084, 0.0597]]),
 torch.float32)

In [18]:
# eg: you wanted a random tensor in the common image shape of [224, 224, 3] ([height, width, color_channels]).

# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [19]:
# Zeros and ones
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype


(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [20]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [ ]:
# Creating a range and tensors like